[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path  = 'forge-cache'
solc_version = "0.8.21"

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
